# nome que vai aparece nas opções da pipe
name: '02. Execução Agendada'

# triggers ou gatilhos de execução
# nesse caso, gatilho agendado = schedule
on:
  schedule:
    - cron: '0 8 * * 1'
# Cron POSIX - CrontabGuru, site para auxiliar a entender
# Minuto - Hora - Dia do Mês - Mês do Ano - Dia da Semana
# Toda 2a feira as 8h am

jobs:
  #descricao job
  e2e-tests:
    #descricao maquin
    runs-on: ubuntu-latest
    #passp a passo
    steps:
      - uses: actions/checkout@v4

      - name: Instalando yarn
        run: npm i -g yarn

      - name: Instalanco dependencia
        run: yarn

      - name: Instalanco playwright
        run: yarn playwright install

      - name: testes e2e
        run: yarn run e2e

      # - name: testes unit
      #   run: yarn run test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio de testes
          path: ./playwright-report
